#!/usr/bin/env python3
# Copyright 2026 Martin Bogomolni
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Turn the .face pixel-art sources into Rust glyph tables.

A face is authored as ASCII art because that is the only form anyone can
usefully review or edit. Hex tables are write-only; a designer cannot see that
the 'e' crossbar sits a row too high by reading 0x7C.

    ./fonts/build.py                 rebuild every face
    ./fonts/build.py cartoon         rebuild one

Output goes to badge-studio/src-tauri/src/font/<id>.rs and is committed, so a
normal build never runs this.
"""
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "badge-studio" / "src-tauri" / "src" / "font"

ROWS = 11
# Glyph rows are u16, so a glyph can be at most this wide. Double-width CJK
# would fit; anything beyond needs a wider row type.
FIELD = 16


class FaceError(Exception):
    pass


def parse(path):
    """Read a .face file into (meta, [(char, advance, [rowstr])])."""
    meta = {}
    glyphs = []
    cur = None  # (char, advance, rows)

    def close():
        if cur is None:
            return
        ch, adv, rows = cur
        if len(rows) != ROWS:
            raise FaceError(f"{path.name}: {ch!r} has {len(rows)} rows, need {ROWS}")
        w = len(rows[0])
        if any(len(r) != w for r in rows):
            raise FaceError(f"{path.name}: {ch!r} has ragged rows")
        if w > FIELD:
            raise FaceError(f"{path.name}: {ch!r} is {w}px, max {FIELD}")
        glyphs.append((ch, adv if adv is not None else meta.get("advance", w), rows))

    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.rstrip("\n")
        # Comments are ';', not '#': a pixel row of eight lit pixels starts
        # with '#', and using it for comments silently ate every glyph whose
        # first row began at x=0. Blank lines separate glyphs, and a row is
        # never blank because an empty row is still eight dots.
        if line.startswith(";") or not line.strip():
            continue
        if line.startswith(":"):
            close()
            # ":A" or ":U+0041" plus an optional "advance=9"
            body = line[1:]
            m = re.match(r"^(U\+[0-9A-Fa-f]{4,6}|.)\s*(?:advance=(\d+))?\s*$", body)
            if not m:
                raise FaceError(f"{path.name}:{lineno}: cannot parse {line!r}")
            token, adv = m.group(1), m.group(2)
            ch = chr(int(token[2:], 16)) if token.startswith("U+") else token
            cur = (ch, int(adv) if adv else None, [])
            continue
        if cur is None:
            k, _, v = line.partition(":")
            if not _:
                raise FaceError(f"{path.name}:{lineno}: expected 'key: value'")
            k = k.strip()
            meta[k] = int(v.strip()) if k in ("advance",) else v.strip()
            continue
        if set(line) - set(".#"):
            raise FaceError(f"{path.name}:{lineno}: rows use only '.' and '#'")
        cur[2].append(line)
    close()

    for key in ("id", "name"):
        if key not in meta:
            raise FaceError(f"{path.name}: missing '{key}:'")
    return meta, glyphs


def pack(rows):
    """Pixel art to u16 rows, bit 15 leftmost so a glyph's x=0 is a fixed bit."""
    out = []
    for r in rows:
        v = 0
        for x, c in enumerate(r):
            if c == "#":
                v |= 1 << (FIELD - 1 - x)
        out.append(v)
    return out


def emit(meta, glyphs):
    name = meta["name"]
    lines = [
        "// Generated by fonts/build.py from fonts/%s.face. Do not edit by hand:" % meta["id"],
        "// edit the .face pixel art and rebuild.",
        "",
        "use super::{Face, Glyph};",
        "",
    ]
    notice = meta.get("notice", "")
    ident = meta["id"].upper().replace("-", "_")
    lines += [
        f"pub static {ident}: Face = Face {{",
        f'    id: "{meta["id"]}",',
        f'    name: "{name}",',
        f'    notice: "{notice}",',
        f"    jitter: &{meta.get('jitter', '[]') or '[]'},",
        f"    pickable: {'false' if meta.get('pickable', 'yes') == 'no' else 'true'},",
        f"    glyphs: GLYPHS,",
        "};",
        "",
        "static GLYPHS: &[(char, Glyph)] = &[",
    ]
    for ch, adv, rows in sorted(glyphs, key=lambda g: g[0]):
        packed = pack(rows)
        lit = "'\\''" if ch == "'" else ("'\\\\'" if ch == "\\" else f"'{ch}'")
        if not ch.isprintable() or ch == " ":
            lit = f"'\\u{{{ord(ch):x}}}'"
        body = ", ".join(f"0x{v:04X}" for v in packed)
        lines.append(f"    ({lit}, Glyph {{ advance: {adv}, rows: [{body}] }}),")
    lines += ["];", ""]
    return "\n".join(lines)


def main():
    want = sys.argv[1:]
    sources = sorted(HERE.glob("*.face"))
    if want:
        sources = [p for p in sources if p.stem in want]
        if not sources:
            raise SystemExit(f"no .face matching {want}")
    OUT.mkdir(parents=True, exist_ok=True)
    for src in sources:
        meta, glyphs = parse(src)
        seen = {}
        for ch, _, _ in glyphs:
            if ch in seen:
                raise FaceError(f"{src.name}: {ch!r} defined twice")
            seen[ch] = True
        dst = OUT / f"{meta['id']}.rs"
        dst.write_text(emit(meta, glyphs))
        widths = {len(r[0]) for _, _, r in glyphs}
        print(f"{src.name}: {len(glyphs)} glyphs, widths {sorted(widths)} -> {dst.name}")


if __name__ == "__main__":
    main()
